# Site
title: Shesh's blog
author: Sheshbabu Chinnakonda

# URL
url: http://www.sheshbabu.com/
root: /
permalink: posts/:title/

prism_plugin:
  mode: "preprocess"
  line_number: false
  custom_css: "themes/minimal/source/styles/highlight.css"

highlight:
  enable: false

language: default

per_page: 50

# Extensions
theme: minimal

sitemap:
  path: sitemap.xml

# Feed
feed:
  type: atom
  limit: false

# Deployment
deploy:
  type: git
  repo: https://github.com/sheshbabu/sheshbabu.github.io
  branch: master
